# Generated by Django 4.1.3 on 2023-01-20 17:16

from django.db import migrations, models
import whiltor.models


class Migration(migrations.Migration):

    dependencies = [
        ('whiltor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=whiltor.models.filepath),
        ),
    ]
