# Generated by Django 4.1.3 on 2023-02-08 08:47

from django.db import migrations, models
import whiltor.models


class Migration(migrations.Migration):

    dependencies = [
        ('whiltor', '0002_alter_card_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='achieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to=whiltor.models.filepath)),
                ('data1', models.CharField(max_length=240)),
            ],
        ),
    ]
